---
title: Data-driven Computational Epidemic Forecasting (with applications in R)
draft: false
event: "F4SG Learning Labs"
event_url: "https://f4sgrn.netlify.app/talks/"
url_pdf= "https://adityalab.cc.gatech.edu/workshops/21-12-01-f4sg-workshop-epi-forecasting.pdf"
url_video= "https://youtube.com/watch?v=VCiDhRxNxgc"
url_code= "https://github.com/AdityaLab/f4sg-epi-workshop"

location: Virtual
summary: "A workshop on Epidemic forecasting research and practice"

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2021-12-01T09:00:00"
date_end: "2021-12-01T13:00:00"
all_day: false
publishdate: "2021-11-05T10:30:00"

categories:
  - training
tags:
  - Epidemic
  - forecasting
  - R
lastmod: '2022-01-04T18:45:00'
featured: no
image:
  caption: ''
  focal_point: 'center'
  preview_only: no
projects: []
---

## Date/time/location

- **Date:** Wednesday 01 December 2021
- **Time:** 09.00-13.00 [Eastern Time](https://time.is/ET), 14.00-18.00 (London)
- **Location:** Virtual/Zoom

## Register for free

You need to register to receive the Zoom link and attend the workshop by Friday 26 November 2021.

[Register here](https://docs.google.com/forms/d/e/1FAIpQLSdF2waMn37ACunuo3g9LnKyRk4pLTRhPTfUG4Xyu9ExMUlTVQ/viewform)

## Instructors

- [Alexander Rodriguez](https://www.cc.gatech.edu/~acastillo41/) 
- [Aditya B. Prakash](https://www.cc.gatech.edu/~badityap/)
- [Harshavardhan Kamarthi](https://www.harsha-pk.com/)

School of Computational Science and Engineering, College of Computing, Georgia Institute of Technology
 

## Who is the training for?

- Anyone who is interested in epidemic forecasting research and practice, from recent machine learning innovations to real-time forecasting challenges;

- A decision maker who wants to learn how forecasts are used in decision making and the tradeoffs of modeling approaches;

- An academic or graduate student that wants to expand their understanding of the state of the art;

- An epidemiologist who wants to complement their knowledge with a data-driven perspective;

## What participants will learn in the training?
 
Participants will be able to:

- Identify modeling approaches and their use in practice.
Distinguish a diverse set of challenges in real-time forecasting;

- Recognize research directions;

- Leverage software for modeling, data acquisition and processing, and evaluation;


## Prerequisites

- Basic knowledge of R or a high-level programming language.

- Basic knowledge of statistics and statistical modeling
 
 
## Outline (4hrs):

1. Epidemic forecasting (0.5 hr)

    - Targets of interest
    - Datasets
    - Evaluation
 
2. Mechanistic models (1 hrs)

    - Introduce basic concepts
    - Mass-action models (Coding example with R)
    - Metapopulation
    - Agent-based models
 
3. Statistical models (1.5 hrs)

    - Google Flu Trends
    - ARIMA (Code example with R)
    - Density estimation
    - Deep learning (Coding example with R, compare with ARIMA)
    - State of the art research
    - Demos
 
4. Hybrid models (0.5 hrs)

    - Discrepancy modeling
    - Ensembles (COVID Forecast ensemble)
 
5. Epidemic forecasting on the ground (0.5 hrs)

    - Real time experiences
    - CDC initiatives
    - Decision making


**[Join Forecasting for Social Good email list](http://eepurl.com/hMFA-9)  to stay informed about upcoming events  **