---
title: Call for Papers on Forecasting for Social Good - International Journal of Forecasting
author: Bahman Rostami-Tabar
date: '2021-09-01'
slug: CFP-IJF
summary: A guide to call for paper papers for forecasting for social in International Journal of Forecasting
categories:
  - Call for Papers
tags:
  - publication
  - forecasting
  - social good
output:
  blogdown::html_page:
    toc: true
    number_sections: false
    toc_depth: 1
---

Forecasting for Social Good (F4SG) aims to explore and expose how (where) forecasting can create positive societal benefits. It aims to tackle real problems in any type of organisations that prioritised the wellbeing of people and the society as a whole towards achieving the Sustainable Development Goals prioritising social foundations and ecological ceilling. It helps managers in domains such as health, humanitarian, public and third sector to improve their practices in using forecasting to support the decision-making system.
Evidence from the first and second workshops on [F4SG](https://www.f4sg.org/services/workshop/) indicated that less attention has been given to research on forecasting for social good in comparison to other areas of forecasting. To address this issue, we organise a special issue of the IJF. The purpose of the special issue is to attract high quality papers that are concerned with forecasting for social good. Both papers on academic forecasting research and applications in forecasting practice are welcome. Areas of interest include, but are not limited to:

- Health and healthcare
- Humanitarian operations
- Disaster relief
- Climate change
- Environment and Wildlife
- Sustainability
- Education
- Public welfare
- Fraud, collusion, and corruption
- Government
- Public safety and security
- Poverty & Inequality
- Social services
- Wellbeing

*Submission deadline : 28 April 2022*


**Guidelines**

- [Submit your paper](https://www.editorialmanager.com/ijf/default.aspx) 

- [Instructions for authors](https://pierrepinson.com/IJF/IJFauthorguidelines.pdf)

All papers will follow IJF’s double-blind refereeing process. For further information about the Special Issue, please contact the guest editors:

- [Dr. Bahman Rostami-Tabar](https://www.bahmanrt.com/), Cardiff University, UK
- [Dr. Michael D. Porter](https://engineering.virginia.edu/faculty/michael-d-porter), University of Virginia, USA
- [Prof. Zied Babai](https://student.kedge.edu/faculty-directory/mohamed-zied-babai), Kedge Business School, France
- [Prof. Pierre Pinson](https://pierrepinson.com/), IJF Editor in Chief, Technical University of Denmark
