---
title: The role of forecasting electricity demand in societal decarbonization (with applications in Python)
draft: false
event: "F4SG Learning Labs"
event_url: "https://f4sgrn.netlify.app/talks/"
#url_slides: "/slides/isf2021.html"
#url_video: ""

location: Virtual
summary: "This talk will provide an overview of the critical role electricity demand forecasting is set to play in societal decarbonization. We will cover some of the core theory behind electricity demand forecasting, and results from recent competitions. Using data at multiple aggregation levels (building, district, country) the talk will be followed by a hands on coding session, where we will show how to create and benchmark different types of electricity forecast algorithms."


# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2022-03-21T14:00:00"
date_end: "2022-03-21T16:00:00"
all_day: false
publishdate: "2021-11-16T10:00:00"

categories:
  - training
tags:
  - electricity
  - environment
  - forecasting
  - python
lastmod: '2021-11-16T10:05:00'
featured: no
image:
  caption: ''
  focal_point: 'center'
  preview_only: no
links:
- icon: images
  icon_pack: fas
  name: slides
  url: pdf/Forecasting_site_electricity_demand.pdf
- icon: github
  icon_pack: fab
  name: materials
  url: https://github.com/hussainkazmi/F4SG
- icon: play-circle
  icon_pack: fab
  name: video
  url: https://www.youtube.com/watch?v=GqVj-t66O24
---

This talk will provide an overview of the critical role electricity demand forecasting is set to play in societal decarbonization. We will cover some of the core theory behind electricity demand forecasting, and results from recent competitions. Using data at multiple aggregation levels (building, district, country) the talk will be followed by a hands on coding session, where we will show how to create and benchmark different types of electricity forecast algorithms.

## Date/time/location

- **Date:** Monday 21 March 2022
- **Time:** 15.00-17.00 [CET Time](https://time.is/CET), 14.00-16.00 (London)


## Registeration & Zoom Link

You need to register to receive the Zoom link and attend the workshop.

[Register here](https://learn.zoom.us/meeting/register/u5IsfuytqjMiHNyrhYarOuZ4DazkxShzQm0t)

## Instructors

- [Hussain Kazmi, KU Leuven](https://www.linkedin.com/in/hussain-kazmi/) 
- [Attila Balint, KU Leuven](https://www.linkedin.com/in/attila-balint-x/)

 
## Who is the training for?

* Anyone who is interested in electricity demand forecasting research and practice, from simple baseline methods to advanced machine learning techniques;
 
* A decision maker who wants to learn how these forecasts can be used in decision making and the tradeoffs of modeling approaches;

* An academic or graduate student that wants to expand their understanding of the state of the art with a hands-on session;

* Practitioners in the field who are looking for ways to improve their data-driven forecasting.

## What participants will learn in the training?
 
Participants will be able to:

* Identify forecasting approaches and their use in predicting electricity demand in practice.

* Distinguish a diverse set of challenges in forecasting electricity demand at multiple scales and how these relate to decision making processes.

* Recognize research directions and better identify numerous sources of open-source electricity datasets.

* Leverage software for modeling, data acquisition and processing, and evaluation.


## Prerequisites

* Basic knowledge of Python or a high-level programming language.

* Basic knowledge of statistics and statistical modeling
 
 
## Outline (2hrs)

The lab session is planned in the form of Jupyter notebooks (using Python)

* Getting familiar with electricity demand data (15 minutes)

* Creating baseline forecasts using the Darts library (15 minutes)

* Creating regression models to predict electricity demand (15 minutes)


**[Join Forecasting for Social Good email list](http://eepurl.com/hMFA-9)  to stay informed about upcoming events  **